import{i,a as m,S as g}from"./assets/vendor-D73Uttp0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const h=document.querySelector("form"),d=document.querySelector(".loader"),p=document.querySelector(".gallery"),s=document.querySelector(".load-more");let l=1,f="",u=40;i.settings({backgroundColor:"#EF4040",titleColor:"#fff",messageColor:"#fff",progressBarColor:"#B51B1B",position:"topRight",onOpening:function(){document.querySelector(".iziToast").style.fontFamily="Montserrat, sans-serif"}});h.addEventListener("submit",t=>{t.preventDefault();const o=document.querySelector(".search-input").value.trim();o?(f=o,l=1,s.style.display="none",p.innerHTML="",y(o)):i.show({message:"Please enter what you are searching for!"})});s.addEventListener("click",()=>{l+=1,s.style.display="none",y(f)});async function y(t){d.style.display="block";const o=new URLSearchParams({key:"28729256-3b1de8368afcf00c1bd7e0c48",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:l,per_page:u});try{const a=(await m.get("https://pixabay.com/api/",{params:o})).data;d.style.display="none",a.hits.length===0&&l===1?i.show({message:"Sorry, there are no images matching your search phrase. Please try again"}):(b(a.hits),a.hits.length<u?(s.textContent="Sorry, no more results",s.setAttribute("disabled","disabled"),s.style.display="block"):(s.textContent="Load more",s.removeAttribute("disabled"),s.style.display="block"))}catch(n){i.show({title:"Error.",message:"Sorry, something went wrong. Please try again."}),console.error(n)}finally{d.style.display="none"}}function b(t){const o=t.map(e=>w(e)).join("");p.insertAdjacentHTML("beforeend",o);const n=p.querySelector(".gallery-item img").getBoundingClientRect().height;if(n){const e=n*2;window.scrollBy({top:e,behavior:"smooth"})}new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function w(t){return`
      <div class="gallery-item">
        <div class="gallery-image"><a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a></div>
        <div class="image-info">
          <span><p>Likes:</p> ${t.likes}</span>
          <span><p>Views:</p> ${t.views}</span>
          <span><p>Comments:</p> ${t.comments}</span>
          <span><p>Downloads:</p> ${t.downloads}</span>
        </div>
      </div>
    `}
//# sourceMappingURL=index.js.map
